Import("*")

srclist = "main.c frames.c libsos.c pager.c timer.c network.c sos_rpc.c sos_rpc_callbacks.c"
liblist = "l4 c ixp_osal ixp400_xscale_sw lwip nfs serial clock elf"

obj = env.KengeProgram("sos", source = Split(srclist), LIBS = Split(liblist))
Return("obj")

# vim: set filetype=python:
